knp_gaufrette:
    stream_wrapper: ~
    adapters:
        upload_adapter:
            local:
                directory: '%app.upload_dir%'

    filesystems:
        uploads_fs:
            adapter: upload_adapter
