vich_uploader:
    db_driver: orm
    storage: gaufrette

    mappings:
        post_poster:
            uri_prefix: /uploads
            # upload_destination: '%kernel.project_dir%/public/uploads'
            upload_destination: uploads_fs
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
