vich_uploader:
    db_driver: orm
    storage: gaufrette

    mappings:
        post_poster:
            uri_prefix: /uploads
            # upload_destination: '%kernel.project_dir%/public/uploads'
            upload_destination: uploads_fs
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: { chars_per_dir: 2, dirs: 3 } # will create directory "a/b" for "abcdef.jpg"
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 18 }
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
