<?php

namespace App\Controller\Admin;

use App\Entity\Post;
use App\Field\ReadOnlyField;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class PostCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Post::class;
    }

    /**
     * @param string $pageName
     * @return iterable
     */
    public function configureFields(string $pageName): iterable
    {
        yield IdField::new('id')
            ->onlyOnIndex();

        yield TextField::new('title');
        yield ReadOnlyField::new('slug');

        yield ChoiceField::new('type')
            ->setChoices([
                'Draft' => Post::TYPE_DRAFT,
                'Published' => Post::TYPE_PUBLISHED,
            ]);

        yield AssociationField::new('category')
            ->setRequired(true);

        yield TextField::new('shortDescription')
            ->onlyOnForms();
        yield TextEditorField::new('description')
            ->hideOnIndex();

        yield AssociationField::new('tags')
            ->hideOnIndex();

        yield AssociationField::new('author')
            ->setRequired(true);
        yield DateTimeField::new('publishedAt');

        yield DateTimeField::new('createdAt')
            ->onlyOnDetail();
        yield DateTimeField::new('updatedAt')
            ->hideOnForm();
    }

    public function configureActions(Actions $actions): Actions
    {
        $actions->add(Crud::PAGE_INDEX, Action::DETAIL);
        return parent::configureActions($actions); // TODO: Change the autogenerated stub
    }


}
