controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type: attribute
    prefix: /manager

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health
